### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by hexappp** [SamuelTulach/voidmap#1]
CRITICAL_STRUCTURE_CORRUPTION
winver 17763.1577

**Comment by SamuelTulach** [comment]
Can you double check that the cr4 value is correct? Respectively if the restored value equals the original? It should be in the minidump if I am not mistaken so if you were to send it I could check it.

**Comment by hexappp** [comment]
[minidump.zip](https://github.com/SamuelTulach/voidmap/files/8191544/minidump.zip)

**Comment by FranklinOP-IND** [comment]
CRITICAL_STRUCTURE_CORRUPTION
version 1809

**Comment by SamuelTulach** [comment]
@hexappp 

![1](https://user-images.githubusercontent.com/16323119/156917428-85713c39-9417-4ac2-b384-842b2e7ff113.png)
![2](https://user-images.githubusercontent.com/16323119/156917431-45557ad0-b208-49e6-b30d-3cdf6ed9a2e3.png)

The value seems to be right, but it's not being written back by the mapper. Are you using the compiled version from UC or did you compile it yourself?

**Comment by SamuelTulach** [comment]
I can also confirm that on my test system it gets written back properly.

![3](https://user-images.githubusercontent.com/16323119/156917663-ef8f8619-056b-4374-bb8f-38a7d39da63c.png)

**Comment by hexappp** [comment]
I just now tried your uc version but cr4 still returns 506f8

**Comment by SamuelTulach** [comment]
> I just now tried your uc version but cr4 still returns 506f8

Well then you'll have to figure out why it fails to trigger on the third time. Since I can't reproduce it I can't really help. Probably a better way would be to write a bit of an assembly and jump out to the the cr4 switch after mapping the driver instead of trying to trigger the exploit one more time. Unfortunately I have some upcoming exams so I will most probably not have time to look into it.

**Comment by hexappp** [comment]
thanks for the information
